events {
    worker_connections 1024;
}

http {
    include /etc/nginx/conf.d/*.conf;

    server {
        listen 80;
        server_name localhost;

        location / {
            return 200 'Sandbox Platform Running';
            add_header Content-Type text/plain;
        }
    }
}
